POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI1YTc0OTdiNDFkNGY0ZTZkOWZhYTk5YzYiLCJpYXQiOjE1MTc3NTQ4MTh9.AcmSTFvPQTN9Z4MHN-6a6AoqBVy0UCCg26pbKzf_FGs

{
  "title": "juttu1",
  "author": "kirjoittaja1",
  "url": "paikka",
  "likes": 6
}